import { getSinglePost } from '@/app/lib/getPosts'
import React from 'react'

export async function generateMetadata({params}){
	const post = await getSinglePost(params.id)
	return {
		title: `${post.title}`,
		description: 'Generated by create next app',
	  }
}
export default async function SinglePostPage({params}) {
  const post = await getSinglePost(params.id)
  return (
	<div className='p-6'>
		<h1 className='text-red-700 text-lg'>{post.title}</h1>
		<p>{post.body}</p>
	</div>
  )
}
