import Comments from '@/app/components/Comments'
import { getSinglePostComments } from '@/app/lib/getPostComments'
import { getSinglePost } from '@/app/lib/getPosts'
import React, { Suspense } from 'react'

export async function generateMetadata({params}){
	const post = await getSinglePost(params.id)
	return {
		title: `${post.title}`,
		description: 'Generated by create next app',
	  }
}

export default async function SinglePostPage({params}) {
  const post = await getSinglePost(params.id)
  const comments = getSinglePostComments(params.id)
  console.log("adnan");
  return (
	<div className='p-6'>
		<h1 className='text-red-700 text-lg'>{post.title}</h1>
		<p>{post.body}</p>
		<hr />
		<Suspense fallback="<h1>loadding for comments</h1>">
           <Comments commentPromise={comments} />
		</Suspense>
	</div>
  )
}
